Replace inline page modification
jenkinsci/embeddable-build-status-plugin pull request #169
Opened 2023-02-12 08:53 UTC by NotMyFault

This PR picks up the last paragraph of https://github.com/jenkinsci/embeddable-build-status-plugin/pull/167 and removes inline page modification.
JavaScript is now loaded via stapler adjuncts and page decoration has been moved to a dedicated CSS file loaded separately, as advised by our documentation.

2023-02-12 12:51 UTC, MarkEWaite requested changes
Thanks very, very much for the pull request and for preparing the plugin for the future content security policy improvements.  When I tested #167, it looked the way I expected.  When I tested this pull request, the input fields did not take the full width of the screen and were wrapped into a single line.

## PR-167 changes

![PR-167-looks-good](https://user-images.githubusercontent.com/156685/218312068-4130ec6b-766d-424a-8136-982951d37c7b.png)

## PR-169 changes

![PR-169-layout-is-more-difficult-to-read](https://user-images.githubusercontent.com/156685/218312125-6c8929bb-99c4-42fd-be47-efc3370c806c.png)

Can the layout in this pull request be adapted to look more like it did in #167?

2023-02-12 12:59 UTC, NotMyFault commented
> When I tested this pull request, the input fields did not take the full width of the screen and were wrapped into a single line.

Good catch! I attempted to load the CSS file from the wrong location, should be good now, quickly checked via `mvn hpi:run` looks fine to me:
![Screenshot 2023-02-12 at 13 59 41](https://user-images.githubusercontent.com/13383509/218312503-7f3bb8ae-70e9-4be9-95ce-feba2e08c553.png)

2023-02-12 13:11 UTC, MarkEWaite approved these changes
Tested interactively and confirmed that it looks good and behaves as it did before.

Thanks very much!

2023-02-12 13:14 UTC, merged

2023-03-09 07:34 UTC, tunsira commented
1edb5e63da455bad86ad79a7d28536d55da79db8