[JENKINS-70464] Test 'EmbeddableBadgeConfigsActionTest'
jenkinsci/embeddable-build-status-plugin pull request #250
Opened 2023-10-08 19:59 UTC by abhishekmaity

In response to #114, 

### Testing done

- addec 'EmbeddableBadgeConfigsActionTest'
- Test coverage shown below

![Screenshot 2023-10-09 012452](https://github.com/jenkinsci/embeddable-build-status-plugin/assets/14294846/66020069-ef47-419b-a52c-c9239510d9cc)

```[tasklist]

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-10-08 22:43 UTC, MarkEWaite requested changes
Please remove the unused mock objects and the two tests that are not testing anything in the target class.

2023-10-08 22:43 UTC, MarkEWaite commented on src/test/java/org/jenkinsci/plugins/badge/actions/EmbeddableBadgeConfigsActionTest.java
> +        Mockito.when(mockRun.getParent()).thenReturn(mockJob);
Not needed and not used.  Please delete these lines since the tests run as expected without them
```suggestion
```

2023-10-08 22:43 UTC, MarkEWaite commented on src/test/java/org/jenkinsci/plugins/badge/actions/EmbeddableBadgeConfigsActionTest.java
> +    }
These tests don't assert any condition about the tested object.  The test name does not match the test that is being performed.  The two tests seem to be asserting that the mock object behaves as defined.  We don't need to test that.
```suggestion
```

2023-10-08 22:43 UTC, MarkEWaite commented on src/test/java/org/jenkinsci/plugins/badge/actions/EmbeddableBadgeConfigsActionTest.java
> +import hudson.model.Run;
Don't need these imports since the mock objects are not needed for the tests as written
```suggestion
```

2023-10-08 22:43 UTC, MarkEWaite commented on src/test/java/org/jenkinsci/plugins/badge/actions/EmbeddableBadgeConfigsActionTest.java
> +import org.mockito.Mockito;
Don't need this object since no mocking is required for the valid tests in the file.
```suggestion
```

2023-10-09 15:35 UTC, abhishekmaity commented
@MarkEWaite changes applied as per suggestion

2023-10-09 16:41 UTC, MarkEWaite approved these changes
Thanks!

2023-10-09 16:41 UTC, merged